spring.application.name=DemoSecurity
spring.datasource.url=jdbc:mysql://localhost:3306/employee_directory
spring.datasource.username=root
spring.datasource.password=arpitarashii88

logging.level.org.springframework.jdbc.core=trace